### ISSUE TITLE
Make it work on linux and windows!

### ISSUE THREAD

**Issue by guilh00009** [jasonjmcghee/rem#111]
please!

**Comment by jasonjmcghee** [comment]
There's another pinned cross-platform issue, but long story short...

I started [a cross platform version a while ago](https://github.com/jasonjmcghee/xrem), but had some trouble attracting other contributers, only have so much free time, and my main platform is mac. Also, my main use case was going back in time and copying something (text from image), which is natively supported on mac and would need to be built from scratch on other platforms.

(Also apple silicon is dramatically more feasible to use long term due to how efficiently it can encode video. Less of an issue on computers with dedicated power though.)
