### ISSUE TITLE
Wen Windows version coming?

### ISSUE THREAD

**Issue by pooriaarab** [jasonjmcghee/rem#23]

**Comment by jasonjmcghee** [comment]
When you convert the code to .NET!

Did what i could: https://chat.openai.com/share/ab35ac3f-fc2c-4f02-9392-e43400d39018

**Comment by jasonjmcghee** [comment]
Try to beat Rewind to market

**Comment by jasonjmcghee** [comment]
Closing for now.

Another idea would be trying to use rust + wgpu for screenshot behavior, and a tesseract wrapper?

**Comment by jasonjmcghee** [comment]
More notes: https://github.com/ndsol/VolcanoSamples/blob/master/09fullscreen/screenshot.cpp

**Comment by jasonjmcghee** [comment]
Theoretically, someone could use _something like_ [Volcano](https://github.com/ndsol/volcano) + [Tesseract](https://github.com/tesseract-ocr/tesseract) etc. and/or go through a make a bunch of functions to figure out what apis to call in order to take a screenshot, then run ocr, etc. same pipeline.

And a graphics layer of some sort. like rust + iced-rs or tauri, or electron, etc.
